name: Run UI Tests on Pull Request

on:
  pull_request:
    branches:
      - cardinal-quarter

jobs:
  test_ui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile # pnpm ya está disponible y en el PATH

      - name: Run Selenium IDE UI Tests
        run: pnpm run test:ui
